/**:
  ros__parameters:
    wheel_radius: 0.033
    track_width: 0.16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad: 651.898160011
    collision_radius: 0.11
    input_noise: 0.0001
    slip_fraction: 0.01
    basic_sensor_variance: 0.0001
    max_range: 10.0
    lidar_min_range: 0.11999999731779099
    lidar_max_range: 3.5
    lidar_angle_increment: 0.01745329238474369
    lidar_num_of_samples: 360
    lidar_resolution: 1
    lidar_noise_variance: 0.0001